# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Monday < Formula
  desc "⚡️ a dev tool for microservice developers to run local applications and/or forwa"
  homepage "https://github.com/eko/monday"
  url "https://github.com/eko/monday/archive/refs/tags/v2.5.0.tar.gz"
  sha256 "bc3ea0e47ed8a4295e9f801d8a8efc5ac1da8e1ea1c82618491b10122041a4af"
  license "MIT"

  def install
    ENV["GOPATH"] = buildpath

    dir = buildpath/"src/github.com/eko/monday"
    dir.install buildpath.children - [buildpath/".brew_home"]

    cd dir do
      system "make build-binary"
      bin.install "monday"

      output = Utils.popen_read("#{bin}/monday completion bash")
      (bash_completion/"monday").write output

      output = Utils.popen_read("#{bin}/monday completion zsh")
      (zsh_completion/"_monday").write output

      prefix.install_metafiles
    end
  end

  test do
    assert_match("Monday - version", shell_output("#{bin}/monday version"))
  end
end
